Fixed installation Exception
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "fspath/setup.py", line 5, in <module>
        import fspath
      File "fspath/fspath/__init__.py", line 4, in <module>
        from .fspath import FSPath
      File "fspath/fspath/fspath.py", line 20, in <module>
        import six
    ImportError: No module named 'six'

When running setup.py we can't import fspath/__init__.py since it
imports FSPath, which need six and six is a pre-requirement which should
be installed by setup.py :P

Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>